name: Generate GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # daily cron
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Stats
        env:
          PAT: ${{ secrets.PAT_TOKEN }}
        run: |
          curl -H "Authorization: token $PAT_ALL_REPOS_TOKEN" \
            "https://github-readme-stats.vercel.app/api?username=AT-GUPTA&show_icons=true&count_private=true&include_all_commits=true&theme=radical" > stats.svg

      - name: Commit Stats
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add stats.svg
          git commit -m "Update GitHub Stats"
          git push
